--
-- Script was generated by Devart dbForge Studio 2019 for SQL Server, Version 5.8.127.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 11/6/2021 2:48:48 PM
-- Server version: 15.00.2000
--

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

INSERT HT_DHCH_ONLINE.dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0000', N'Mai An Nhật ', '0587771321', N'432 Phan Tây Hồ, Xã Phú Mỹ Hưng, Nam Định', 'Keenan126@gmail.com')
INSERT HT_DHCH_ONLINE.dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0001', N'Vương Thu Đạt ', '0964768912', N'628 rần Văn Ơn, Xã Vĩnh Lộc A, Lâm Đồng', 'Bryson@nowhere.com')
INSERT HT_DHCH_ONLINE.dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0002', N'Cao Hoài Vũ ', '0985103772', N'051 Hồ Chí Minh - Trung Lương, Phường An Phú, Nghệ An', 'WinnieLavoie@nowhere.com')
INSERT HT_DHCH_ONLINE.dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0003', N'Phạm Minh Lộc ', '0365250286', N'637 Đường Số 10, Phường Tăng Nhơn Phú A, Yên Bái', 'Cristy_Higgins339@gmail.com')
INSERT HT_DHCH_ONLINE.dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0004', N'Vũ Duy An ', '0980777430', N'568 Hẻm 160 Võ Thị Sáu, Xã Quy Đức, Tây Ninh', 'Acker@gmail.com')
INSERT HT_DHCH_ONLINE.dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0005', N'Hồ Duy Yến ', '0331402073', N'766 Phạm Văn Bạch, Phường 28, Yên Bái', 'oycoxhpj_ommxw@gmail.com')
INSERT HT_DHCH_ONLINE.dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0006', N'La Quốc Sang ', '0986609057', N'903 Hoa Sứ, Xã Đông Thạnh, Lai Châu', 'Joette_Doe@nowhere.com')
INSERT HT_DHCH_ONLINE.dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0007', N'Võ Thu Thảo ', '0939288631', N'106 Xô Viết Nghệ Tĩnh, Phường Tân Phú, Tây Ninh', 'EloisU_Alaniz877@gmail.com')
INSERT HT_DHCH_ONLINE.dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0008', N'Hồ Thu Mẫn ', '0354831742', N'235 ẻm 91 Trần Quốc Hoàn, Phường Thạnh Mỹ Lợi, Hải Phòng', 'rklb5435@gmail.com')
INSERT HT_DHCH_ONLINE.dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0009', N'La Bảo Đông ', '0900354600', N'511 Phổ Quang, Phường 11, Hà Nam', 'Desantis@gmail.com')
INSERT HT_DHCH_ONLINE.dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0010', N'Tạ Vân Phương ', '0381412062', N'155 Ngô Chí Quốc, Phường Cầu Kho, Bình Thuận', 'AbbyTrotter644@nowhere.com')
INSERT HT_DHCH_ONLINE.dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0011', N'Trần Tuấn Triết ', '0587132793', N'585 Bùi Quang Là, Phường Sơn Kỳ, Khánh Hòa', 'Caudill@gmail.com')
INSERT HT_DHCH_ONLINE.dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0012', N'Bùi Hồng Điệp ', '0364531035', N'787 Hẻm 12 Nguyễn Thị Minh Khai, Xã Tân Thạnh Đông, Hậu Giang', 'AngeloHyman34@gmail.com')
INSERT HT_DHCH_ONLINE.dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0013', N'Đặng Ngọc Tâm ', '0769234851', N'433 Nguyễn Văn Thủ, Phường 04, Thanh Hóa', 'BillyeBingham1@gmail.com')
INSERT HT_DHCH_ONLINE.dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0014', N'Đinh Quốc Đăng ', '0851351944', N'273 3 Tháng 2, Phường Bình Hưng Hoà B, Tuyên Quang', 'Abney@gmail.com')
INSERT HT_DHCH_ONLINE.dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0015', N'Đặng Thụy Phong ', '0971172902', N'028 Ngô Quyền, Phường Thảo Điền, Khánh Hòa', 'Winford_Mckenzie@gmail.com')
INSERT HT_DHCH_ONLINE.dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0016', N'Dương Đức Anh ', '0332513878', N'298 Trần Quang Khải, Xã Bình Khánh, Vĩnh Long', 'VinesQ@nowhere.com')
INSERT HT_DHCH_ONLINE.dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0017', N'Ngô Duy Hân ', '0353196770', N'566 Huỳnh Mẫn Đạt, Phường Bình Hưng Hoà A, Bình Định', 'AudraHammons@gmail.com')
INSERT HT_DHCH_ONLINE.dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0018', N'Hoàng Thu Nguyên ', '0906458856', N'219 oàng Văn Thụ, Phường Nguyễn Cư Trinh, Trà Vinh', 'HeathAddison@gmail.com')
INSERT HT_DHCH_ONLINE.dbo.KhachHang(MaKH, HoTen, SDT, DiaChi, Email) VALUES (N'KH0019', N'La Bá Thuyên ', '0762799293', N'508 Lê Văn Sỹ, Xã Thạnh An, Quảng Trị', 'Neuman6@gmail.com')
GO