--
-- Script was generated by Devart dbForge Studio 2019 for SQL Server, Version 5.8.127.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 11/6/2021 2:48:49 PM
-- Server version: 15.00.2000
--

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

INSERT HT_DHCH_ONLINE.dbo.TaiXe(CMND, HoTen, SDT, DiaChi, BienSoXe, KVHoatDong, Email, STK, NganHang, ChiNhanh) VALUES (N'012317983262', N'Huỳnh Bá Vỹ ', '0828062836', N'186 3 Tháng 2, Xã Phong Phú, Đồng Tháp', N'41-C9-187.39', NULL, 'Abby.WWilhelm33@example.com', '740967112771615', NULL, NULL)
INSERT HT_DHCH_ONLINE.dbo.TaiXe(CMND, HoTen, SDT, DiaChi, BienSoXe, KVHoatDong, Email, STK, NganHang, ChiNhanh) VALUES (N'047733459124', N'Tô Huy Thành ', '0791601467', N'066 Nguyễn Hoàng, Phường Nguyễn Cư Trinh, Kiên Giang', N'54-T4-412.97', NULL, 'Adam_Rosenbaum361@example.com', '969707017812531', NULL, NULL)
INSERT HT_DHCH_ONLINE.dbo.TaiXe(CMND, HoTen, SDT, DiaChi, BienSoXe, KVHoatDong, Email, STK, NganHang, ChiNhanh) VALUES (N'060149634642', N'Hoàng Gia Thủy ', '0337347034', N'968 Nguyễn Xí, Phường Nguyễn Thái Bình, Tuyên Quang', N'45-D8-651.55', NULL, 'Hunter.KTodd563@nowhere.com', '770633944378149', NULL, NULL)
INSERT HT_DHCH_ONLINE.dbo.TaiXe(CMND, HoTen, SDT, DiaChi, BienSoXe, KVHoatDong, Email, STK, NganHang, ChiNhanh) VALUES (N'076074349923', N'Trần Hoài Tuấn ', '0701894751', N'891 Bạch Đằng, Phường 21, Phú Yên', N'13-M6-627.90', NULL, 'CrystleCupp674@nowhere.com', '0704900097', NULL, NULL)
INSERT HT_DHCH_ONLINE.dbo.TaiXe(CMND, HoTen, SDT, DiaChi, BienSoXe, KVHoatDong, Email, STK, NganHang, ChiNhanh) VALUES (N'116194696615', N'Nguyễn Đức Khoa ', '0794653565', N'529 Ngụy Như Kon Tum, Phường Tân Phú, Long An', N'57-I2-459.65', NULL, 'Thrasher594@example.com', '652733044163436', NULL, NULL)
INSERT HT_DHCH_ONLINE.dbo.TaiXe(CMND, HoTen, SDT, DiaChi, BienSoXe, KVHoatDong, Email, STK, NganHang, ChiNhanh) VALUES (N'145947105913', N'Đinh Tiến Hân ', '0813906950', N'003 Đa Phước, Phường Tân Định, Bắc Kạn', N'43-C5-254.67', NULL, NULL, '190491275345373', NULL, NULL)
INSERT HT_DHCH_ONLINE.dbo.TaiXe(CMND, HoTen, SDT, DiaChi, BienSoXe, KVHoatDong, Email, STK, NganHang, ChiNhanh) VALUES (N'287438544537', N'Dương Hồng Hậu ', '0869901143', N'146 Nguyễn Thị Thập, Phường Phước Long B, Phú Yên', N'14-J5-429.34', NULL, 'Bader@example.com', '564727767305675', NULL, NULL)
INSERT HT_DHCH_ONLINE.dbo.TaiXe(CMND, HoTen, SDT, DiaChi, BienSoXe, KVHoatDong, Email, STK, NganHang, ChiNhanh) VALUES (N'299376200742', N'Dương Hùng Trân ', '0394817837', N'494 3 Tháng 2, Phường An Phú Đông, Nghệ An', N'75-N2-007.04', NULL, 'Alejandro.Sells@example.com', '170361247122467', NULL, NULL)
INSERT HT_DHCH_ONLINE.dbo.TaiXe(CMND, HoTen, SDT, DiaChi, BienSoXe, KVHoatDong, Email, STK, NganHang, ChiNhanh) VALUES (N'572059128444', N'Đặng Hoài Toàn ', '0791244557', N'440 Nguyễn Thị Định, Xã Bình Khánh, Quảng Bình', N'78-G3-358.80', NULL, 'rooooq8207@example.com', '256424850656367', NULL, NULL)
INSERT HT_DHCH_ONLINE.dbo.TaiXe(CMND, HoTen, SDT, DiaChi, BienSoXe, KVHoatDong, Email, STK, NganHang, ChiNhanh) VALUES (N'576257330725', N'Đoàn Đức Thành ', '0397263634', N'807 ��m 78 Tôn Thất Thuyết, Phường Phạm Ngũ Lão, Tuyên Quang', N'21-V0-528.60', NULL, 'AdellaMyers8@example.com', '696771688706592', NULL, NULL)
INSERT HT_DHCH_ONLINE.dbo.TaiXe(CMND, HoTen, SDT, DiaChi, BienSoXe, KVHoatDong, Email, STK, NganHang, ChiNhanh) VALUES (N'595971112137', N'Lê Thị Khoa ', '0359237240', N'991 Nguyễn Chánh Sắt, Xã Lê Minh Xuân, Bắc Ninh', N'36-K0-430.31', NULL, 'Easter@example.com', '5045438508', NULL, NULL)
INSERT HT_DHCH_ONLINE.dbo.TaiXe(CMND, HoTen, SDT, DiaChi, BienSoXe, KVHoatDong, Email, STK, NganHang, ChiNhanh) VALUES (N'629027773508', N'Hồ Hùng Ngân ', '0928762178', N'495 Trịnh Đình Thảo, Xã Tân Thạnh Đông, Đắk Nông', N'21-F6-608.69', NULL, 'Monahan172@example.com', '827673581204969', NULL, NULL)
INSERT HT_DHCH_ONLINE.dbo.TaiXe(CMND, HoTen, SDT, DiaChi, BienSoXe, KVHoatDong, Email, STK, NganHang, ChiNhanh) VALUES (N'705671300636', N'Vũ An Hân ', '0357734740', N'625 Kênh 19 Tháng 5 B, Phường Đông Hưng Thuận, Cao Bằng', N'98-P6-317.67', NULL, 'Alane_Jacks@example.com', '375579851487915', NULL, NULL)
INSERT HT_DHCH_ONLINE.dbo.TaiXe(CMND, HoTen, SDT, DiaChi, BienSoXe, KVHoatDong, Email, STK, NganHang, ChiNhanh) VALUES (N'720918092001', N'Cao Quang Sơn ', '0393985617', N'444 An Dương Vương, Xã Phú Mỹ Hưng, Sơn La', N'79-Y5-551.39', NULL, 'ggzl79@example.com', '4075812998', NULL, NULL)
INSERT HT_DHCH_ONLINE.dbo.TaiXe(CMND, HoTen, SDT, DiaChi, BienSoXe, KVHoatDong, Email, STK, NganHang, ChiNhanh) VALUES (N'736684870422', N'Tô Hồng Ngân ', '0962601655', N'013 Cầu Vượt Linh Xuân, Phường Tân Thuận Tây, Lào Cai', N'16-K6-083.54', NULL, 'ColettaCardenas@example.com', '6682136072', NULL, NULL)
INSERT HT_DHCH_ONLINE.dbo.TaiXe(CMND, HoTen, SDT, DiaChi, BienSoXe, KVHoatDong, Email, STK, NganHang, ChiNhanh) VALUES (N'802940979194', N'Ngô Gia Trân ', '0937995045', N'881 Nguyễn Hữu Thọ, Xã Bình Mỹ, Bắc Kạn', N'53-H4-863.67', NULL, 'Hinton@example.com', '1758900866', NULL, NULL)
INSERT HT_DHCH_ONLINE.dbo.TaiXe(CMND, HoTen, SDT, DiaChi, BienSoXe, KVHoatDong, Email, STK, NganHang, ChiNhanh) VALUES (N'877193442696', N'Nguyễn Thu Tân ', '0564360962', N'893 Thuận Kiều, Phường Long Trường, Nam Định', N'62-Z6-377.03', NULL, 'MartyBair2@nowhere.com', '491230501178489', NULL, NULL)
INSERT HT_DHCH_ONLINE.dbo.TaiXe(CMND, HoTen, SDT, DiaChi, BienSoXe, KVHoatDong, Email, STK, NganHang, ChiNhanh) VALUES (N'895605791558', N'Lữ Bảo Cường ', '0702204288', N'268 Bạch Đằng, Xã Thới Tam Thôn, Yên Bái', N'63-A5-246.63', NULL, 'Truitt@nowhere.com', '8236328114', NULL, NULL)
INSERT HT_DHCH_ONLINE.dbo.TaiXe(CMND, HoTen, SDT, DiaChi, BienSoXe, KVHoatDong, Email, STK, NganHang, ChiNhanh) VALUES (N'911190252461', N'Hồ Bá Luân ', '0864310359', N'349 Cầu Kênh Tẻ, Phường Thủ Thiêm, Bắc Giang', N'09-E3-220.56', NULL, 'BernieAckerman48@example.com', '177468290507746', NULL, NULL)
INSERT HT_DHCH_ONLINE.dbo.TaiXe(CMND, HoTen, SDT, DiaChi, BienSoXe, KVHoatDong, Email, STK, NganHang, ChiNhanh) VALUES (N'916857316033', N'La Thụy Thúy ', '0339320413', N'087 Mai Văn Vĩnh, Xã Tân Thạnh Tây, Đồng Tháp', N'18-P8-908.51', NULL, NULL, '553119297358254', NULL, NULL)
GO