--
-- Script was generated by Devart dbForge Studio 2019 for SQL Server, Version 5.8.127.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 11/6/2021 2:48:48 PM
-- Server version: 15.00.2000
--

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

INSERT HT_DHCH_ONLINE.dbo.DoiTac(MaDT, MSThue, TenDT, TenNgDaiDien, ThanhPho, Quan, SoChiNhanh, SoLuongDH, LoaiHang, DiaChi, SDT, Email) VALUES (N'DT000', '68741', N'Lock & Lock', N'Trần Duy Công ', N'TP.HCM', N'Quận Bình Tân', 1, NULL, N'Hàng tiêu dùng', N'46 ', '0761747636', 'locknlock@gmail.com')
INSERT HT_DHCH_ONLINE.dbo.DoiTac(MaDT, MSThue, TenDT, TenNgDaiDien, ThanhPho, Quan, SoChiNhanh, SoLuongDH, LoaiHang, DiaChi, SDT, Email) VALUES (N'DT001', '27856', N'Dirty Coins', N'Phạm Thụy Nhật ', N'TP.HCM', N'Quận Bình Thạnh', 6, NULL, N'Thời trang', N'85 ', '0924243047', 'dirtycoins@gmail.com')
INSERT HT_DHCH_ONLINE.dbo.DoiTac(MaDT, MSThue, TenDT, TenNgDaiDien, ThanhPho, Quan, SoChiNhanh, SoLuongDH, LoaiHang, DiaChi, SDT, Email) VALUES (N'DT002', '23381', N'Thái Dương', N'Huỳnh Ngọc Uyên ', N'TP.HCM', N'Quận 1', 1, NULL, N'Mỹ phẩm', N'04 ', '0861857028', 'thaiduong@gmail.com')
INSERT HT_DHCH_ONLINE.dbo.DoiTac(MaDT, MSThue, TenDT, TenNgDaiDien, ThanhPho, Quan, SoChiNhanh, SoLuongDH, LoaiHang, DiaChi, SDT, Email) VALUES (N'DT003', '53873', N'Rohto', N'Phùng Gia Ân ', N'TP.HCM', N'Quận Tân Bình', 0, NULL, N'Dược phẩm', N'694 ', '0358378217', 'rohto@gmail.com')
INSERT HT_DHCH_ONLINE.dbo.DoiTac(MaDT, MSThue, TenDT, TenNgDaiDien, ThanhPho, Quan, SoChiNhanh, SoLuongDH, LoaiHang, DiaChi, SDT, Email) VALUES (N'DT004', '54625', N'Laneige', N'Tô Đức Hưng ', N'TP.HCM', N'Quận Gò Vấp', 4, NULL, N'Mỹ phẩm', N'61 ', '0324284281', 'laneige@gmail.com')
INSERT HT_DHCH_ONLINE.dbo.DoiTac(MaDT, MSThue, TenDT, TenNgDaiDien, ThanhPho, Quan, SoChiNhanh, SoLuongDH, LoaiHang, DiaChi, SDT, Email) VALUES (N'DT005', '91651', N'Deli', N'Hoàng Hoài Trí ', N'TP.HCM', N'Huyện Cần Giờ', 6, NULL, N'Văn phòng phẩm', N'53 ', '0829434225', 'deli@gmail.com')
INSERT HT_DHCH_ONLINE.dbo.DoiTac(MaDT, MSThue, TenDT, TenNgDaiDien, ThanhPho, Quan, SoChiNhanh, SoLuongDH, LoaiHang, DiaChi, SDT, Email) VALUES (N'DT006', '30762', N'Pentel', N'Lưu Thị Tùng ', N'TP.HCM', N'Quận 9', 2, NULL, N'Văn phòng phẩm', N'034 ', '0831475807', 'pentel@gmail.com')
INSERT HT_DHCH_ONLINE.dbo.DoiTac(MaDT, MSThue, TenDT, TenNgDaiDien, ThanhPho, Quan, SoChiNhanh, SoLuongDH, LoaiHang, DiaChi, SDT, Email) VALUES (N'DT007', '33445', N'Converse', N'Võ Thanh Mẫn ', N'TP.HCM', N'Quận Bình Thạnh', 0, NULL, N'Thời trang', N'273 ', '0981851596', 'converse@gmail.com')
INSERT HT_DHCH_ONLINE.dbo.DoiTac(MaDT, MSThue, TenDT, TenNgDaiDien, ThanhPho, Quan, SoChiNhanh, SoLuongDH, LoaiHang, DiaChi, SDT, Email) VALUES (N'DT008', '96680', N'NutiFood', N'Hồ Tuấn Tuệ ', N'TP.HCM', N'Quận 8', 6, NULL, N'Thực phẩm đồ uống', N'342 ', '0399331881', 'nutifood@gmail.com')
INSERT HT_DHCH_ONLINE.dbo.DoiTac(MaDT, MSThue, TenDT, TenNgDaiDien, ThanhPho, Quan, SoChiNhanh, SoLuongDH, LoaiHang, DiaChi, SDT, Email) VALUES (N'DT009', '13830', N'Cosrx', N'Vũ Tuấn Tú ', N'TP.HCM', N'Quận 1', 2, NULL, N'Mỹ phẩm', N'63 ', '0781585247', 'corsx@gmail.com')
INSERT HT_DHCH_ONLINE.dbo.DoiTac(MaDT, MSThue, TenDT, TenNgDaiDien, ThanhPho, Quan, SoChiNhanh, SoLuongDH, LoaiHang, DiaChi, SDT, Email) VALUES (N'DT010', '57701', N'Thiên Long', N'Phạm Minh Thiết ', N'TP.HCM', N'Quận 6', 4, NULL, N'Văn phòng phẩm', N'434 ', '0378895581', 'thienlong@gmail.com')
INSERT HT_DHCH_ONLINE.dbo.DoiTac(MaDT, MSThue, TenDT, TenNgDaiDien, ThanhPho, Quan, SoChiNhanh, SoLuongDH, LoaiHang, DiaChi, SDT, Email) VALUES (N'DT011', '01612', N'Vinamilk', N'Phan Minh Gấm ', N'TP.HCM', N'Quận Tân Phú', 1, NULL, N'Thực phẩm đồ uống', N'617 ', '0862117475', 'vinamilk@gmail.com')
INSERT HT_DHCH_ONLINE.dbo.DoiTac(MaDT, MSThue, TenDT, TenNgDaiDien, ThanhPho, Quan, SoChiNhanh, SoLuongDH, LoaiHang, DiaChi, SDT, Email) VALUES (N'DT012', '32239', N'3CE', N'Võ Hồng Luân ', N'TP.HCM', N'Quận Bình Thạnh', 0, NULL, N'Mỹ Phẩm', N'34 ', '0333486011', 'cos3ce@gmail.com')
INSERT HT_DHCH_ONLINE.dbo.DoiTac(MaDT, MSThue, TenDT, TenNgDaiDien, ThanhPho, Quan, SoChiNhanh, SoLuongDH, LoaiHang, DiaChi, SDT, Email) VALUES (N'DT013', '51924', N'Cocoon', N'Trần Ngọc Đan ', N'TP.HCM', N'Quận 1', 4, NULL, N'Mỹ phẩm', N'63 ', '0777205876', 'cocoon@gmail.com')
INSERT HT_DHCH_ONLINE.dbo.DoiTac(MaDT, MSThue, TenDT, TenNgDaiDien, ThanhPho, Quan, SoChiNhanh, SoLuongDH, LoaiHang, DiaChi, SDT, Email) VALUES (N'DT014', '10258', N'Biti''s', N'Hoàng Tú Liêm ', N'TP.HCM', N'Quận Gò Vấp', 6, NULL, N'Thời trang', N'36 ', '0906029399', 'bitis@gmail.com')
INSERT HT_DHCH_ONLINE.dbo.DoiTac(MaDT, MSThue, TenDT, TenNgDaiDien, ThanhPho, Quan, SoChiNhanh, SoLuongDH, LoaiHang, DiaChi, SDT, Email) VALUES (N'DT015', '87953', N'Philips', N'Phạm Khắc Ly ', N'TP.HCM', N'Quận Bình Tân', 3, NULL, N'Hàng tiêu dùng', N'38 ', '0862446515', 'philips@gmail.com')
INSERT HT_DHCH_ONLINE.dbo.DoiTac(MaDT, MSThue, TenDT, TenNgDaiDien, ThanhPho, Quan, SoChiNhanh, SoLuongDH, LoaiHang, DiaChi, SDT, Email) VALUES (N'DT016', '72947', N'Watson', N'Trần Minh Khải ', N'TP.HCM', N'Quận Bình Tân', 1, NULL, N'Mỹ phẩm', N'52 ', '0393336715', 'watson@gmail.com')
INSERT HT_DHCH_ONLINE.dbo.DoiTac(MaDT, MSThue, TenDT, TenNgDaiDien, ThanhPho, Quan, SoChiNhanh, SoLuongDH, LoaiHang, DiaChi, SDT, Email) VALUES (N'DT017', '81075', N'Maybelline', N'Ngô Hồng Trí ', N'TP.HCM', N'Quận 4', 1, NULL, N'Mỹ phẩm', N'191 ', '0344685401', 'maybelline@gmail.com')
INSERT HT_DHCH_ONLINE.dbo.DoiTac(MaDT, MSThue, TenDT, TenNgDaiDien, ThanhPho, Quan, SoChiNhanh, SoLuongDH, LoaiHang, DiaChi, SDT, Email) VALUES (N'DT018', '08138', N'PNJ', N'Lữ Văn Mai ', N'TP.HCM', N'Quận 5', 5, NULL, N'Trang sức', N'630 ', '0960208489', 'pnj@gmail.com')
INSERT HT_DHCH_ONLINE.dbo.DoiTac(MaDT, MSThue, TenDT, TenNgDaiDien, ThanhPho, Quan, SoChiNhanh, SoLuongDH, LoaiHang, DiaChi, SDT, Email) VALUES (N'DT019', '40908', N'Traphaco', N'Tô Đình Nhu ', N'TP.HCM', N'Quận 10', 5, NULL, N'Dược phẩm', N'148 ', '0981123673', 'traphaco@gmail.com')
GO