--
-- Script was generated by Devart dbForge Studio 2019 for SQL Server, Version 5.8.127.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 11/19/2021 1:19:44 PM
-- Server version: 15.00.2000
--

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

INSERT HT_DHCH_ONLINE.dbo.CT_TTDH(MaTinhTrang, Mota) VALUES (0, N'Đơn hàng đã hủy')
INSERT HT_DHCH_ONLINE.dbo.CT_TTDH(MaTinhTrang, Mota) VALUES (1, N'Đơn hàng đang được tiếp nhận')
INSERT HT_DHCH_ONLINE.dbo.CT_TTDH(MaTinhTrang, Mota) VALUES (2, N'Đơn hàng đang đóng gói')
INSERT HT_DHCH_ONLINE.dbo.CT_TTDH(MaTinhTrang, Mota) VALUES (3, N'Đang chờ giao hàng')
INSERT HT_DHCH_ONLINE.dbo.CT_TTDH(MaTinhTrang, Mota) VALUES (4, N'Đơn hàng đang giao')
INSERT HT_DHCH_ONLINE.dbo.CT_TTDH(MaTinhTrang, Mota) VALUES (5, N'Đơn hàng giao thành công')
GO